# Generated by Django 5.0.9 on 2024-11-26 11:49

import homsapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', homsapp.models.UserManager()),
            ],
        ),
    ]
